language: python
python:
  - 2.7
  - 3.5

before_script:
  - pip install -r tests/requirements.txt

script:
  - python runtests.py

notifications:
  slack:
    - secure: "03MBcWtrc5he8XgmCNkL0g32C2oCpQk/UbJlC/EHbO4QHUPugJULxVL0jDr28DBImd4aZJbNM8GAyqRa54gB00PG/7x9gHPbv0ic1VvyIuir2LWIfNFiswNN9YCFb2oil/Dje0SH0is6YbM/5ite9x4tKPmuhnewSuCVIld8e65R5zRkmbBCDBr246HdaC8vFF0rlyRIAYMyWsEX6iNffEaje5HbiED7GLvj0GzK/WRnFh2UfW+5GqcqwAg1SWb6HyLdur80y9owCGc9aM6toiy+olanBKm8P5uu7bsIIdZdlPuslfEGV5ZvL9Zq20/7RJztHp3sQHd1ivr2A1t7V/CqT6w5GwlC7bOpuRnZJtTt4wqyWfYO0BXNgTw/h0Bob2vke2BcvdYvvNViZBS1oADgAhkbmZTDpMDp9Ju6cRNSR56i3U13krEmG7q8td3+NiilrfQs2qJhGqyFryWQZ0eHdvwgR4yl7WrsO4W/ctLcrHfBIM5U2PAYEJkmn9e6bXGzzXM7uy/+Jrtzqh8d6HEo3Y8AqfGoriT1z/GeXhiluM4BwxiBq7HYGRDueX4WXHFqBCaX5ksKVWX/RRUK7PMs2C3xCzo8r+eFuCOE0ahAfAO3sufu48thNd5QmccFrub8ahSc5xdQHKeO9PoBS5DlFPJ/Cy415xQC3sVJxsc="
